services:
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - cheezypizza
    volumes:
      - redis_data:/data

  coturn:
    image: coturn/coturn
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 60000-60128:60000-60128/udp

    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes

    command: >
      -n
      --log-file=stdout
      --redis-userdb="ip=redis connect_timeout=30"
      --min-port=60000
      --max-port=60128

    networks:
      - cheezypizza

  cheezypizza:
    build: .

    image: hariharjeevan/cheezypizza:latest

    ports:
      - "0.0.0.0:3000:3000"

    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - COTURN_ENABLED=true

    networks:
      - cheezypizza

    depends_on:
      - redis

    env_file:
      - .env

networks:
  cheezypizza:
    driver: bridge

volumes:
  redis_data: