services:
  redis:
    image: redis:latest
    container_name: cheezypizza-redis

    ports:
      - "6379:6379"

    networks:
      - cheezypizza

    volumes:
      - redis_data:/data

  coturn:
    image: coturn/coturn
    container_name: cheezypizza-coturn

    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"

      # Uncomment for TURN relay traffic
      # - "49152-65535:49152-65535/udp"

    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes

    command: >
      -n
      --log-file=stdout
      --redis-userdb="ip=redis connect_timeout=30"

    networks:
      - cheezypizza

    depends_on:
      - redis

  cheezypizza:
    build: .

    image: hariharjeevan/cheezypizza:latest

    container_name: cheezypizza

    ports:
      - "3000:3000"

    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379

    networks:
      - cheezypizza

    depends_on:
      - redis

networks:
  cheezypizza:
    driver: bridge

volumes:
  redis_data: